package com.citricl.music.domain;

public class Recommend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.iid
     *
     * @mbggenerated
     */
    private Integer iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.val
     *
     * @mbggenerated
     */
    private Double val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.uid
     *
     * @return the value of recommend.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.uid
     *
     * @param uid the value for recommend.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.iid
     *
     * @return the value of recommend.iid
     *
     * @mbggenerated
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.iid
     *
     * @param iid the value for recommend.iid
     *
     * @mbggenerated
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.val
     *
     * @return the value of recommend.val
     *
     * @mbggenerated
     */
    public Double getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.val
     *
     * @param val the value for recommend.val
     *
     * @mbggenerated
     */
    public void setVal(Double val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.time
     *
     * @return the value of recommend.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.time
     *
     * @param time the value for recommend.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}