package com.citricl.music.domain;

public class SongCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count.song_id
     *
     * @mbggenerated
     */
    private Integer songId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count.cnt
     *
     * @mbggenerated
     */
    private Long cnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count.id
     *
     * @return the value of count.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count.id
     *
     * @param id the value for count.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count.uid
     *
     * @return the value of count.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count.uid
     *
     * @param uid the value for count.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count.song_id
     *
     * @return the value of count.song_id
     *
     * @mbggenerated
     */
    public Integer getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count.song_id
     *
     * @param songId the value for count.song_id
     *
     * @mbggenerated
     */
    public void setSongId(Integer songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count.cnt
     *
     * @return the value of count.cnt
     *
     * @mbggenerated
     */
    public Long getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count.cnt
     *
     * @param cnt the value for count.cnt
     *
     * @mbggenerated
     */
    public void setCnt(Long cnt) {
        this.cnt = cnt;
    }
}