package com.citricl.music.dao;

import com.citricl.music.domain.RecommendList;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RecommendListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_list
     *
     * @mbggenerated
     */
    int insert(RecommendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_list
     *
     * @mbggenerated
     */
    int insertSelective(RecommendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_list
     *
     * @mbggenerated
     */
    RecommendList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecommendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecommendList record);

    List<RecommendList> allRecommedList(Integer id, Long time);
}