package com.citricl.music.dao;

import com.citricl.music.domain.Recommend;
import org.springframework.stereotype.Repository;

@Repository
public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int insertSelective(Recommend record);

    int update(Recommend record);

    Recommend select(Recommend record);
}