package com.citricl.music.dao;

import com.citricl.music.domain.SongCount;
import org.springframework.stereotype.Repository;

@Repository
public interface SongCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated
     */
    int insert(SongCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated
     */
    int insertSelective(SongCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated
     */
    SongCount select(SongCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SongCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count
     *
     * @mbggenerated
     */
    int update(SongCount record);
}